### ISSUE TITLE
Uploading an image to a remote server prompts a “CORS” error

### ISSUE THREAD

**Issue by ghost** [Creling/obsidian-image-uploader#5]
Hi,
  I have encountered an error when using image uploader,The error message viewed through the developer tools is related to CORS.
obsidian version:0.15.9
image uploader :0.2
Uploading images using IP addresses is successful
![Snipaste_2022-09-10_02-59-29](https://user-images.githubusercontent.com/58515931/189426583-617b61af-14a2-432d-9e2a-02502ba34d0e.png)
Uploading images using a domain name prompts an error
![Snipaste_2022-09-10_03-00-16](https://user-images.githubusercontent.com/58515931/189426973-00ce2258-d8c4-4da3-9c14-f6856d26336a.png)
![Snipaste_2022-09-10_03-02-42](https://user-images.githubusercontent.com/58515931/189427009-c0d6b2b2-3c78-432c-ba2f-afd1a4c99426.png)
![Snipaste_2022-09-10_03-14-09](https://user-images.githubusercontent.com/58515931/189427027-a203b026-be24-4cc7-ab9c-026b228503b9.png)

**Comment by Creling** [comment]
Hello, this error is caused by a mis-configure on your backend server, please refer https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information.

To solve this problem, you could add `Access-Control-Allow-Origin` header in your NGINX/Apache config file.

https://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx
